name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: {}

concurrency:
  group: "ci"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    # the system must match the one in .github/workflows/Dockerfile-ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: false
          cache: true
      - name: Build Go code
        env:
          GOOS: linux
          CGO_ENABLED: 0
        run: go build -v -o gargantua
      # TODO: lint, sonar, tests, etc.
      - name: Build Docker image
        if: |
          github.event_name == 'push' && (
            startsWith(github.event.ref, 'refs/tags/')
            || endsWith(github.event.ref, '/master')
          )
        run: docker build -t hobbyfarm/gargantua:${GIT_COMMIT_SHORT_HASH:-dev} -f .github/workflows/Dockerfile-ci .
