# GitHub configuration
# - Settings > Secrets > Actions > Repository secrets: DOCKER_HUB_USER, DOCKER_HUB_PASSWORD

name: PKG

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: {}

env:
  CONTAINER_REPOSITORY: hobbyfarm/gargantua

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build container image
        if: |
          github.event_name == 'push' && (
            startsWith(github.event.ref, 'refs/tags/')
            || endsWith(github.event.ref, '/master')
          )
        run: docker build -t $CONTAINER_REPOSITORY:${GIT_COMMIT_SHORT_HASH:-dev} -f Dockerfile .
      - name: Compute container image tag
        if: |
          github.event_name == 'push' && (
            startsWith(github.event.ref, 'refs/tags/')
            || endsWith(github.event.ref, '/master')
          )
        id: compute_docker_tag
        run: |
          tag=${GITHUB_REF#refs/tags/}
          branch=${GITHUB_REF#refs/heads/}
          if [ "$tag" != "$GITHUB_REF" ]; then
            tag=$(echo "$tag" | sed -e 's/[^a-zA-Z0-9\-\.]/-/g')
            echo ::set-output name=DOCKER_TAG::${tag}
          elif [ "$branch" != "$GITHUB_REF" ]; then
            branch=$(echo "$branch" | sed -e 's/[^a-zA-Z0-9\-\.]/-/g')
            echo ::set-output name=DOCKER_TAG::${branch}
          else
            echo "unable to determine docker tag" >&2
            exit 1
          fi
      - name: Login container registry
        if: |
          github.event_name == 'push' && (
            startsWith(github.event.ref, 'refs/tags/')
            || endsWith(github.event.ref, '/master')
          )
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" \
            | docker login -u "${{ secrets.DOCKER_HUB_USER }}" --password-stdin
      - name: Tag container image
        if: |
          github.event_name == 'push' && (
            startsWith(github.event.ref, 'refs/tags/')
            || endsWith(github.event.ref, '/master')
          )
        run: |
          docker tag \
            $CONTAINER_REPOSITORY:${GIT_COMMIT_SHORT_HASH:-dev} \
            $CONTAINER_REPOSITORY:${{ steps.compute_docker_tag.outputs.DOCKER_TAG }}
      - name: Push container image to registry
        if: |
          github.event_name == 'push' && (
            startsWith(github.event.ref, 'refs/tags/')
            || endsWith(github.event.ref, '/master')
          )
        run: |
          docker push $CONTAINER_REPOSITORY:${{ steps.compute_docker_tag.outputs.DOCKER_TAG }}
      - name: Create container image latest tag
        if: |
          github.event_name == 'push' && (
            startsWith(github.event.ref, 'refs/tags/')
          )
        run: |
          docker tag \
            $CONTAINER_REPOSITORY:${GIT_COMMIT_SHORT_HASH:-dev} \
            $CONTAINER_REPOSITORY:latest
      - name: Push latest tag
        if: |
          github.event_name == 'push' && (
            startsWith(github.event.ref, 'refs/tags/')
          )
        run: |
          docker push $CONTAINER_REPOSITORY:latest
